Banking_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('user/', include('userauths.urls')),
    path('account/', include('account.urls')),
]




urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views


app_name = "core"

urlpatterns = [ 
    path('', views.IndexTemplateView.as_view(), name="index"),
    path('freelancer-payments/', views.FreelancerPayments.as_view(), name="freelancer-payments"),
    path('subscriptions/', views.SubscriptionsView.as_view(), name="subscriptions"),
    path('security/', views.SecurityTemplateView.as_view(), name="security"),
    path('fees/', views.FeesTemplateView.as_view(), name="fees"),
    path('business-account/', views.BusinessAccountTemplate.as_view(), name="business-account"),
    path('corporate-card/', views.CorporateCardTemplate.as_view(), name="corporate-card"),
    path('expense-management/', views.ExpenseManagementTemplate.as_view(), name="expense-management"),
    path('budget/', views.BudgetTemplate.as_view(), name="budget"),
    path('integration/', views.IntegrationsTemplate.as_view(), name="integration"),
    path('company/', views.CompanyTemplate.as_view(), name="company"),
    path('career/', views.CareerTemplate.as_view(), name="career"),
    path('blog/', views.BlogTemplate.as_view(), name="blog"),

    # Transfers
    path('search-account/', views.SearchUsersByAccountNumberView.as_view(), name="search-account"),
    path('amount-transfer/<str:account_number>/', views.AmountTransferView.as_view(), name="amount-transfer"),
    path('amount-transfer-process/<str:account_number>/', views.AmountTransferProcessView.as_view(), name="amount-transfer-process"),
    path('transfer-confirmation/<str:account_number>/<str:transaction_id>/', views.TransferConfirmation.as_view(), name="transfer-confirmation"),
    path('transfer-process/<str:account_number>/<str:transaction_id>/', views.TransferProcessView.as_view(), name="transfer-process"),
    path('transfer-completed/<str:account_number>/<str:transaction_id>/', views.TransferCompletedView.as_view(), name="transfer-completed"),
  
    # Transactions
    path('transaction-list/', views.TransactionListView.as_view(), name="transaction-list"),
    path('transaction-detail/<str:transaction_id>/', views.TransactionDetailView.as_view(), name='transaction-detail'),

    # Payment Request
    path('request-search-account/', views.SearchUsersRequest.as_view(), name="request-search-account"),
    path('amount-request/<str:account_number>/', views.AmountRequest.as_view(), name="amount-request"),
    path('amount-request-process/<str:account_number>/', views.AmountRequestProcessView.as_view(), name="amount-request-process"),
    path('amount-request-confirmation/<str:account_number>/<str:transaction_id>/', views.AmountRequestConfirmation.as_view(), name="amount-request-confirmation"),
    path('amount-request-final-process/<str:account_number>/<str:transaction_id>/', views.AmountRequestFinalProcessView.as_view(), name="amount-request-final-process"),
    # path("amount-request-final-process/<account_number>/<transaction_id>/", views.AmountRequestFinalProcess, name="amount-request-final-process"),
    path('amount-request-completed/<str:account_number>/<str:transaction_id>/', views.RequestCompleted.as_view(), name="amount-request-completed"),
   
     # Request Settlement
     path('settlement-confirmation/<str:account_number>/<str:transaction_id>/', views.SettlementConfirmation.as_view(), name="settlement-confirmation"),
     path('settlement-processing/<str:account_number>/<str:transaction_id>/', views.SettlementProcessing.as_view(), name="settlement-processing"),
     path('settlement-completed/<str:account_number>/<str:transaction_id>/', views.SettlementCompleted.as_view(), name="settlement-completed"),
     path("delete-request/<str:account_number>/<str:transaction_id>/", views.DeletePaymentRequest.as_view(), name="delete-request"),
    # path('delete-request/account_number>/transaction_id/', views.DeletePaymentRequest, name="delete-request"),

    # Credit Card
    path('card-detail/<str:card_id>/', views.CreditCardDetail.as_view(), name="card-detail"),
    path('fund-credit-card/<str:card_id>/', views.FundCreditCardView.as_view(), name="fund-credit-card"),
    path('withdraw-fund/<str:card_id>/', views.WithdrawFundView.as_view(), name="withdraw-fund"),
    path('delete-card/<str:card_id>/', views.DeleteCardView.as_view(), name="delete-card"),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path('sign-up/', views.SignupView.as_view(), name="sign-up"),
    path('sign-in/', views.LoginView.as_view(), name="sign-in"),
    path("sign-out/", views.LogoutView.as_view(), name="sign-out"),
]

templates/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Paylio - Money Transfer and Online Payments HTML Template</title>
    
    <link rel="shortcut icon" href="{% static 'assets/images/fav.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/arafat-font.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>

<body>
      <!-- start preloader -->
      <div class="preloader" id="preloader"></div>
      <!-- end preloader -->

    <a href="javascript:void(0)" class="scrollToTop"><i class="fas fa-angle-double-up"></i></a>

    <header class="header-section">
        <div class="overlay">
            <div class="container">
                <div class="row d-flex header-area">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="index.html">
                            <img src="{% static 'assets/images/logo.png' %}" class="logo" alt="logo">
                        </a>
                        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbar-content">
                            <i class="fas fa-bars"></i>
                        </button>
                        <div class="collapse navbar-collapse justify-content-end" id="navbar-content">
                            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="javascript:void(0)"
                                        data-bs-toggle="dropdown" data-bs-auto-close="outside">Personal</a>
                                    <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="{% url 'core:freelancer-payments' %}">Freelancer Payments</a></li>
                                        <li><a class="nav-link" href="{% url 'core:subscriptions' %}">Subscriptions</a></li>
                                        <li><a class="nav-link" href="{% url 'core:security' %}">Security</a></li>
                                        <li><a class="nav-link" href="{% url 'core:fees' %}">Fees</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="javascript:void(0)"
                                        data-bs-toggle="dropdown" data-bs-auto-close="outside">Business</a>
                                    <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="{% url 'core:freelancer-payments' %}">Business Payments</a></li>
                                        <li><a class="nav-link" href="{% url 'core:business-account' %}">Business Account</a></li>
                                        <li><a class="nav-link" href="{% url 'core:corporate-card' %}">Corporate Card</a></li>
                                        <li><a class="nav-link" href="{% url 'core:expense-management' %}">Expense Management</a></li>
                                        <li><a class="nav-link" href="{% url 'core:budget' %}">Budgeting</a></li>
                                        <li><a class="nav-link" href="{% url 'core:integration' %}">Integrations</a></li>
                                        <li><a class="nav-link" href="{% url 'core:security' %}">Security</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="javascript:void(0)"
                                        data-bs-toggle="dropdown" data-bs-auto-close="outside">Company</a>
                                    <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="{% url 'core:company' %}">About Us</a></li>
                                        <li><a class="nav-link" href="{% url 'core:career' %}">Career</a></li>
                                        <li class="dropend sub-navbar">
                                            <a href="javascript:void(0)" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown"
                                              data-bs-auto-close="outside">Blog</a>
                                            <ul class="dropdown-menu sub-menu shadow">
                                                <li><a class="nav-link" href="{% url 'core:blog' %}">Blog</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <div class="right-area header-action d-flex align-items-center max-un">
                                {% if request.user.is_authenticated %}
                                <a href="/admin" class="login cmdn-btn">Admin</a>
                                <a href="{% url 'userauths:sign-out' %}" class="login cmn-btn">Sign Out</a>
                                {% else %}
                                <a href="{% url 'userauths:sign-in' %}" class="login">Login</a>
                                <a href="{% url 'userauths:sign-up' %}" class="cmn-btn">Sign Up
                                    <i class="fas fa-caret-right"></i>
                                </a>
                                {% endif %}
                                
                            </div>
                        </div>
                    </nav>
                </div>
                <!-- alert start -->
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}">
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <script>
                    setTimeout (() => {
                        $(".alert").alert("close");
                    }, 4000)
                </script>
                <!-- alert end -->
            </div>
        </div>
    </header>
    <!-- header-section end -->

{% block content %}
  
{% endblock content %}


    
    <!--==================================================================-->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/fontawesome.js' %}"></script>
    <script src="{% static 'assets/js/plugin/slick.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/counter.js' %}"></script>
    <script src="{% static 'assets/js/plugin/waypoint.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/plugin.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>