Banking_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('user/', include('userauths.urls')),
    path('account/', include('account.urls')),
]




urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views


app_name = "core"

urlpatterns = [ 
    path('', views.IndexTemplateView.as_view(), name="index"),
    path('freelancer-payments/', views.FreelancerPayments.as_view(), name="freelancer-payments"),
    path('subscriptions/', views.SubscriptionsView.as_view(), name="subscriptions"),
    path('security/', views.SecurityTemplateView.as_view(), name="security"),
    path('fees/', views.FeesTemplateView.as_view(), name="fees"),
    path('business-account/', views.BusinessAccountTemplate.as_view(), name="business-account"),
    path('corporate-card/', views.CorporateCardTemplate.as_view(), name="corporate-card"),
    path('expense-management/', views.ExpenseManagementTemplate.as_view(), name="expense-management"),
    path('budget/', views.BudgetTemplate.as_view(), name="budget"),
    path('integration/', views.IntegrationsTemplate.as_view(), name="integration"),
    path('company/', views.CompanyTemplate.as_view(), name="company"),
    path('career/', views.CareerTemplate.as_view(), name="career"),
    path('blog/', views.BlogTemplate.as_view(), name="blog"),

    # Transfers
    path('search-account/', views.SearchUsersByAccountNumberView.as_view(), name="search-account"),
    path('amount-transfer/<str:account_number>/', views.AmountTransferView.as_view(), name="amount-transfer"),
    path('amount-transfer-process/<str:account_number>/', views.AmountTransferProcessView.as_view(), name="amount-transfer-process"),
    path('transfer-confirmation/<str:account_number>/<str:transaction_id>/', views.TransferConfirmation.as_view(), name="transfer-confirmation"),
    path('transfer-process/<str:account_number>/<str:transaction_id>/', views.TransferProcessView.as_view(), name="transfer-process"),
    path('transfer-completed/<str:account_number>/<str:transaction_id>/', views.TransferCompletedView.as_view(), name="transfer-completed"),
  
    # Transactions
    path('transaction-list/', views.TransactionListView.as_view(), name="transaction-list"),
    path('transaction-detail/<str:transaction_id>/', views.TransactionDetailView.as_view(), name='transaction-detail'),

    # Payment Request
    path('request-search-account/', views.SearchUsersRequest.as_view(), name="request-search-account"),
    path('amount-request/<str:account_number>/', views.AmountRequest.as_view(), name="amount-request"),
    path('amount-request-process/<str:account_number>/', views.AmountRequestProcessView.as_view(), name="amount-request-process"),
    path('amount-request-confirmation/<str:account_number>/<str:transaction_id>/', views.AmountRequestConfirmation.as_view(), name="amount-request-confirmation"),
    path('amount-request-final-process/<str:account_number>/<str:transaction_id>/', views.AmountRequestFinalProcessView.as_view(), name="amount-request-final-process"),
    # path("amount-request-final-process/<account_number>/<transaction_id>/", views.AmountRequestFinalProcess, name="amount-request-final-process"),
    path('amount-request-completed/<str:account_number>/<str:transaction_id>/', views.RequestCompleted.as_view(), name="amount-request-completed"),
   
     # Request Settlement
     path('settlement-confirmation/<str:account_number>/<str:transaction_id>/', views.SettlementConfirmation.as_view(), name="settlement-confirmation"),
     path('settlement-processing/<str:account_number>/<str:transaction_id>/', views.SettlementProcessing.as_view(), name="settlement-processing"),
     path('settlement-completed/<str:account_number>/<str:transaction_id>/', views.SettlementCompleted.as_view(), name="settlement-completed"),
     path("delete-request/<str:account_number>/<str:transaction_id>/", views.DeletePaymentRequest.as_view(), name="delete-request"),
    # path('delete-request/account_number>/transaction_id/', views.DeletePaymentRequest, name="delete-request"),

    # Credit Card
    path('card-detail/<str:card_id>/', views.CreditCardDetail.as_view(), name="card-detail"),
    path('fund-credit-card/<str:card_id>/', views.FundCreditCardView.as_view(), name="fund-credit-card"),
    path('withdraw-fund/<str:card_id>/', views.WithdrawFundView.as_view(), name="withdraw-fund"),
    path('delete-card/<str:card_id>/', views.DeleteCardView.as_view(), name="delete-card"),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path('sign-up/', views.SignupView.as_view(), name="sign-up"),
    path('sign-in/', views.LoginView.as_view(), name="sign-in"),
    path("sign-out/", views.LogoutView.as_view(), name="sign-out"),
]

core/forms.py
from django import forms
from .models import *

class CreditCardForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Card Holder Name"}))
    number = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"Card Number"}))
    month = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"Expiry Month"}))
    year = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"Expiry Month"}))
    cvv = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"CVV"}))

    class Meta:
        model = CreditCard
        fields = ['name', 'number', 'month', 'year', 'cvv', 'card_type']
    

core/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, UpdateView, CreateView, DetailView, DeleteView, ListView, View
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import ListView
from account.models import Account
from .models import *
from .forms import *
from django.contrib import messages
from decimal import Decimal
from django.db.models import F
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

#<-------------------------Index View Starts From Here--------------------------------------->
class IndexTemplateView(TemplateView):
    template_name = 'core/index.html'


#<---------------------------Freelancer Payments Template View Starts From Here------------------------->
class FreelancerPayments(TemplateView):
    template_name = 'core/freelancer-payments.html'


#<--------------------------------------------Subscriptions Template View Starts From Here-------------------------->
class SubscriptionsView(TemplateView):
    template_name = 'core/subscriptions.html'

#<-------------------------------------------Security Template View Starts From Here------------------------>
class SecurityTemplateView(TemplateView):
    template_name = 'core/security.html'

#<-------------------------------------------Fees Template View Starts From Here---------------------------->
class FeesTemplateView(TemplateView):
    template_name = 'core/fees.html'

#<------------------------------------------Business Account Template View Starts From Here---------------------------->
class BusinessAccountTemplate(TemplateView):
    template_name = 'core/business-account.html'

#<------------------------------------------Corporate Card Starts From Here-------------------------------------------->
class CorporateCardTemplate(TemplateView):
    template_name = 'core/corporate-card.html'

#<--------------------------------------------Expense Management Starts From Here--------------------------------------->
class ExpenseManagementTemplate(TemplateView):
    template_name = 'core/expense-management.html'

#<-----------------------------------------------Budget Template Starts From Here--------------------------------------->
class BudgetTemplate(TemplateView):
    template_name = 'core/budget.html'

#<-----------------------------------------------Integrations Template Starts from Here---------------------------------->
class IntegrationsTemplate(TemplateView):
    template_name = 'core/integration.html'

#<-----------------------------------------------Company(Paylio) Template Starts From Here------------------------------->
class CompanyTemplate(TemplateView):
    template_name = 'core/company.html'         

#<----------------------------------------------Carrer Template View Starts From Here------------------------------------>
class CareerTemplate(TemplateView):
    template_name = 'core/career.html'

#<----------------------------------------------Blog Template View Starts From Here--------------------------------------->
class BlogTemplate(TemplateView):
    template_name = 'core/blog.html'            


############################################## TRANSAFER ######################################

#<------------------------------Search Account View Starts from Here---------------------->
class SearchUsersByAccountNumberView(LoginRequiredMixin, ListView):
    template_name = 'transfer/search-user-by-account-number.html'
    model = Account
    context_object_name = 'account'

    def post(self, request, *args, **kwargs):
        queryset = self.model.objects.all()
        query = self.request.POST.get("account_number")

        if query:
            queryset = queryset.filter(
                Q(account_number=query) |
                Q(account_id=query)
            ).distinct()

        context = {'account': queryset, 'query': query}
        return render(request, self.template_name, context)


#<------------------------------------------Amount Transfer View Starts From Here--------------------------->
class AmountTransferView(TemplateView):
    template_name = 'transfer/amount-transfer.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        account_number = kwargs.get('account_number')
        try:
            account = Account.objects.get(account_number=account_number)
        except Account.DoesNotExist:
            context['redirect_to_search'] = True
            return context
        context['account'] = account
        return context


    def get(self, request, *args, **kwargs):
        # Get the context data
        context = self.get_context_data(**kwargs)
        
        # Check if the 'redirect_to_search' key is present in the context
        if context.get('redirect_to_search'):
            messages.warning(self.request, "Account does not exist.")
            return redirect("core:search-account")

        # Render the template with the valid context
        return self.render_to_response(context)


#<-------------------------------------Amount Transfer Process View Starts From Here--------------------------------->
class AmountTransferProcessView(View):

    def get(self, request, account_number, *args, **kwargs):
        account = Account.objects.get(account_number=account_number)
        sender = request.user
        reciever = account.user
        sender_account = request.user.account
        reciever_account = account

        context = {
            'account': account,
            'sender': sender,
            'reciever': reciever,
            'sender_account': sender_account,
            'reciever_account': reciever_account,
        }

        return render(request, self.template_name, context)

    def post(self, request, account_number, *args, **kwargs):
        account = Account.objects.get(account_number=account_number)
        sender = request.user
        reciever = account.user
        sender_account = request.user.account
        reciever_account = account

        amount = request.POST.get("amount-send")
        description = request.POST.get("description")


        if sender_account.account_balance >= Decimal(amount):
            new_transaction = Transaction.objects.create(
                user=request.user,
                amount=amount,
                description=description,
                reciever=reciever,
                sender=sender,
                sender_account=sender_account,
                 reciever_account= reciever_account,
                status="processing",
                transaction_type="transfer"
            )
            new_transaction.save()

            transaction_id = new_transaction.transaction_id
            return redirect("core:transfer-confirmation", account.account_number, transaction_id)
        else:
            messages.warning(request, "Insufficient Fund.")
            return redirect("core:amount-transfer", account.account_number)



#<---------------------------------------Transfer Confirmation----------------------------------------->
class TransferConfirmation(TemplateView):
    template_name = "transfer/transfer-confirmation.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        account_number = kwargs.get('account_number')
        transaction_id = kwargs.get('transaction_id')
        try: 
            account = get_object_or_404(Account, account_number=account_number)
            transaction = get_object_or_404(Transaction, transaction_id=transaction_id)
        except:
            messages.warning(self.request, "Transaction does not exist.")
            return redirect("account:account")
        messages.success(self.request, "Transaction details loaded successfully.")
        context["account"] = account
        context["transaction"] = transaction
        return context

#<----------------------------------------------Transfer Process view Starts From Here-------------------------->
class TransferProcessView(View):

    def get(self, request, account_number, transaction_id, *args, **kwargs):
        account = get_object_or_404(Account, account_number=account_number)
        transaction = get_object_or_404(Transaction, transaction_id=transaction_id)

        sender = request.user
        reciever = account.user

        sender_account = request.user.account
        reciever_account = account

        context = {
            'account': account,
            'transaction': transaction,
            'sender': sender,
            'reciever': reciever,
            'sender_account': sender_account,
            'reciever_account': reciever_account,
            'completed': False,
        } 
        return render(request, self.template_name, context)

    
    def post(self, request, account_number, transaction_id, *args, **kwargs):
        account = get_object_or_404(Account, account_number=account_number)
        transaction = get_object_or_404(Transaction, transaction_id=transaction_id)

        sender = request.user
        reciever = account.user

        sender_account = request.user.account
        reciever_account = account

        completed = False

        pin_number = request.POST.get("pin-number")
        # print("---------------------->>>>>>>>>>>>>>", pin_number)

        if pin_number == sender_account.pin_number:
            transaction.status = "Completed"
            transaction.save()

            sender_account.account_balance -= transaction.amount
            sender_account.save()

            account.account_balance += transaction.amount
            account.save()

            # Notification.objects.create(
            #     amount=transaction.amount,
            #     user=account.user,
            #     notification_type="Credit Alert"
            # )

            # Notification.objects.create(

templates/core/integration.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<!-- Banner Section start -->
<section class="banner-section business-account integrations">
    <div class="overlay">
        <div class="banner-content">
            <div class="container wow fadeInUp">
                <div class="row justify-content-center align-items-center">
                    <div class="col-lg-10">
                        <div class="main-content text-center">
                            <div class="top-area section-text dark-sec">
                                <h5 class="sub-title">Budgeting and Analytics</h5>
                                <h1 class="title">Automate Your Workflows With Direct Integrations</h1>
                                <p>Close the books faster, without errors.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="banner-img-bottom pb-120">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-10">
                    <div class="img-area">
                        <img src="{% static 'assets/images/integrations-banner.png' %}" alt="image">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Banner Section end -->

<!-- Features start -->
<section class="earn-cashback features">
    <div class="overlay pb-120">
        <div class="container wow fadeInUp">
            <div class="row pb-120 align-items-center justify-content-between">
                <div class="col-md-6">
                    <div class="section-area">
                        <h5 class="sub-title">Close the books in record time</h5>
                        <h2 class="title">Sync With Your Favourite Software</h2>
                        <p>Automate book-keeping and reconciliation, and avoid manual errors with direct integrations to your accounting software.</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="sec-image">
                        <img src="{% static 'assets/images/integrations-features-1.png' %}" alt="image" class="w-100">
                    </div>
                </div>
            </div>
            <div class="row pb-120 align-items-center justify-content-between">
                <div class="col-md-6 order-md-0 order-1">
                    <div class="sec-image">
                        <img src="{% static 'assets/images/integrations-features-2.png' %}" alt="image" class="w-100">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="section-area">
                        <h2 class="title">Intelligent categorisation that halves your work</h2>
                        <p>Save hours each month with intelligent categorisation and automated general ledger mapping to your accounting software.</p>
                    </div>
                </div>
            </div>
            <div class="row align-items-center justify-content-between">
                <div class="col-md-6">
                    <div class="section-text">
                        <h2 class="title">Integrated invoicing and reconcilation</h2>
                        <p>Send invoices directly from your Paylio account. When a payment is received, the invoice will be automatically marked as paid and reconciled.</p>
                    </div>
                    <div class="btn-area">
                        <a href="{% url 'userauths:sign-up' %}" class="cmn-btn">Try it out</a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="sec-image ex-mar">
                        <img src="{% static 'assets/images/integrations-features-3.png' %}" alt="image" class="w-100">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Features end -->

<!-- Platform integration start -->
<section class="call-action integration">
    <div class="overlay pt-120 pb-120">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-8 text-center">
                    <div class="section-text">
                        <h5 class="sub-title">Platform integration</h5>
                        <h2 class="title">Integrate Plugins to Start Accepting Payments in Minutes</h2>
                        <p>We make integrating with the most popular e-commerce platforms seamless. Customise, or enjoy out-of-the-box features.</p>
                    </div>
                    <div class="btn-area">
                        <a href="{% url 'userauths:sign-up' %}" class="cmn-btn">Open a Free Account</a>
                        <a href="" class="cmn-btn active">Talk to an expert</a>
                    </div>
                    <ul class="mt-60">
                        <li><img src="{% static 'assets/images/icon/aws.png' %}" alt="icon"></li>
                        <li><img src="{% static 'assets/images/icon/shopify.png' %}" alt="icon"></li>
                        <li><img src="{% static 'assets/images/icon/magento.png' %}" alt="icon"></li>
                        <li><img src="{% static 'assets/images/icon/xero.png' %}" alt="icon"></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Platform integration end -->

<!-- Call Action start -->
<section class="call-action">
    <div class="overlay pt-120">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-6 text-center">
                    <div class="section-text">
                        <h5 class="sub-title">What are you waiting for?</h5>
                        <h2 class="title">Make Global Payments Simple Today</h2>
                        <p>No-fuss company cards for team members, instant virtual cards for security and flexibility — all set up with our easy expense management</p>
                    </div>
                    <div class="btn-area">
                        <a href="{% url 'userauths:sign-up' %}" class="cmn-btn">Sign up in minutes</a>
                        <a href="" class="cmn-btn active">Talk to an expert</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Call Action end -->

<!-- Footer Area Start -->
<footer class="footer-section">
    <div class="container pt-120">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="newsletter">
                    <div class="section-area mb-30 dark-sec text-center">
                        <h3 class="title">Subscribe to Our Newsletter</h3>
                    </div>
                    <form action="#">
                        <div class="form-group d-flex align-items-center">
                            <input type="text" placeholder="Your Email Address">
                            <button><img src="{% static 'assets/images/icon/arrow-right-2.png' %}" alt="icon"></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer-area pt-120">
            <div class="footer-top">
                <div class="row align-items-center">
                    <div class="col-sm-6 d-flex justify-content-center justify-content-sm-start">
                        <div class="menu-item">
                            <ul class="footer-link d-flex align-items-center">
                                <li><a href="about-us.html">About Us</a></li>
                                <li><a href="help-center.html">Support</a></li>
                                <li><a href="fees.html">Fees</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-link d-flex justify-content-sm-end justify-content-center align-items-center">
                            <a href="javascript:void(0)"><img src="{% static 'assets/images/icon/facebook.png' %}" alt="icon"></a>
                            <a href="javascript:void(0)"><img src="{% static 'assets/images/icon/linkedin.png' %}" alt="icon"></a>
                            <a href="javascript:void(0)"><img src="{% static 'assets/images/icon/instagram.png' %}" alt="icon"></a>
                            <a href="javascript:void(0)"><img src="{% static 'assets/images/icon/twitter.png' %}" alt="icon"></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-bottom">
                <div class="row justify-content-between align-items-center">
                    <div class="col-md-6 col-sm-8 d-flex justify-content-center justify-content-sm-start order-sm-0 order-1">
                        <div class="copyright text-center text-sm-start">
                            <p> Copyright © 2023 <a href="{% url 'core:index' %}">Paylio.</a> All Rights Reserved.</p>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-4">
                        <div class="menu-item">
                            <ul class="footer-link d-flex justify-content-sm-end justify-content-center align-items-center">
                                <li><a href="terms-conditions.html">Terms</a></li>
                                <li><a href="privacy-policy.html">Privacy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Area End -->

{% endblock %}